name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # Runner instalado no próprio EC2
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Corrigido: alinhamento correto
    
      - name: Create .env file
        run: |
          cat <<EOF > .env
          DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
          DB_PORT=${{ secrets.DB_PORT }}
          NODE_ENV=production
          PORT=${{ secrets.PORT }}
          EOF

      - name: Copy .env to project directory
        run: |
          cp .env /home/ubuntu/desafio-backend-seven/
      
      - name: Make deploy.sh executable and run it
        run: |
          cd /home/ubuntu/desafio-backend-seven
          chmod +x deploy.sh
          ./deploy.sh